spring:
  datasource:
    url: jdbc:mysql://localhost:3307/food_deliver
    username: root
    password: qweedc@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  servlet:
    context-path: /api
  port: 8080





